theme: jekyll-theme-slate

title: DialogOS

github:
  repository_url: https://github.com/coli-saar/dialogos
  zip_url: /dialogos.zip
  
show_downloads: "true"


release:
  tag: v2.0.0
  version: v2_0_0
