theme: jekyll-theme-slate

title: DialogOS

github:
  repository_url: https://github.com/dialogos-project/dialogos
  zip_url: /dialogos.zip

show_downloads: "true"


release:
  tag: 2.1.1
  version: "2_1_1"
