theme: jekyll-theme-slate

title: DialogOS

github:
  repository_url: https://github.com/dialogos-project/dialogos
  zip_url: /dialogos.zip
  
show_downloads: "true"


release:
  tag: v2.0.1
  version: "2_0_1"
